---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: fhd-portal-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAepbDflWsLq/ssLG6ITuEBVz16UYTDweXlJRvTGwZMOTR6+1ZW9yW4xAPHZVqCcrGmjjGSgAusXZLj1EPpG/GJkg04l3Gv2UdMnOFLyTcS+92lkmnJ1eQymwaau3yHe05/dKwcmf43X/gRQFdF+ufXXyFJMZzHut/EjLLBHGG54O3hv+w6I5TEgjvkDrddXaNWtn39c2iWfnA2isrL0Itl3Ss36JEgeaYueXAKr/CgrRwgZ/muM5Sbn98DN6JZ51HKvX1uIW+nrp7kj7uBJZ2GUiPxEzhf5fCTd4h499p8G4YyE+723AnLFBEldQf9tko4yTxFwzYUiqT5xNEU5EjgZ6qX48OnNPS2Uf/yKbA+SssIjt3z8pgzIz+URivUewcYeuiTDxWEYU7yvsZS+UMtq9NbQhYmL4esIm5AmEXy3lReLG5gPeps4DtDa6hzEoYa7UDfVENP6iJZnX7teM0WKatClLQ469xuJuPKld64uIDDIi0s9GDkQStRFvVSSvRVDRtSri/hkbP5XjOCwSvilON90YRiwPpjGHiPV4dD4X3HPZkuCDH7386W1zSOx6xKi9xdVOFOiza6AtJTpzU0wYCVV/rcV7BDSC8cTPEMPBnWMZVXLlUV09pqmot0EW7K+vVf504ozB7ne+PVv9C6scE/ziecoyudtgl9+MKDuzXZWQ2FOk/1XKMnJzrW/7ChORD/nJoeebhPT6xgvOiVS17+UGnZigGVb69jJ4pT9gHe43rxHKSjtuNCjjz4V93ONdpg4ALK3dkGyN3Xb0e22AujO9zFJ89KLI1YATizkGC1UbYpbTwFsRS8PZdibR6iF9GL1JJOxJnMkhLYYihpc8th9sY4JI3bPk1BPp8eDHqIl44pyVh7o3OKhYd+QQ0wKCRL/U9tgc6fYHUuVF6aq3xQJIkOEZVWuH2NVTeJZv6GWJ7FranG0x63HhBo3y/N808LbAcz6yS/XummYlBqag==
  template:
    metadata:
      name: registry-credentials
      namespace: fhd-portal-dev
    type: kubernetes.io/dockerconfigjson
