---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: fhd-portal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-sa
  namespace: fhd-portal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver-sa
  namespace: fhd-portal
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit-php-sa
  namespace: fhd-portal